language: php

php:
  - 5.3

before_script:
  - composer install -d workbench/northwestern/printer
  - composer --prefer-source --dev install
  - rm -f app/database/production.sqlite
  - touch app/database/production.sqlite
  - php artisan migrate